# Modo de despliegue
nube=no

# Interfaz
editorLayout=si
editarUsuarios=si

# Actualización
tiempoRefresco=5000

# Fecha/hora (formato ISO-8601, leído como LocalDateTime)
inicioDeActividades=2026-01-01T08:00:00
